version: '3'

services:
  sspanel:
    # build: .    # <---- 如果需要最新代码，取消本行注释并注释下面一行
    image: ghcr.io/kleinrui/sspanel-uim:latest
    container_name: sspanel
    restart: always
    network_mode: bridge
    ports:
      - 8080:80   # <---- 更改为你服务器上的端口
    environment:
      - DB_ROOT_PWD=${DB_ROOT_PWD}
      - DB_SSPANEL_PWD=${DB_SSPANEL_PWD}
    volumes:
      - ./config/.config.php:/www/SSPanel-Uim/config/.config.php
      - ./config/appprofile.php:/www/SSPanel-Uim/config/appprofile.php
      - ./storage/:/www/SSPanel-Uim/storage/
      - ./mariadb/:/srv/mariadb/  # 用于使用 /srv/mariadb/mysqld.sock 连接数据库
    user: www-data:www-data
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
      - MYSQL_DATABASE=sspanel
      - MYSQL_USER=sspanel
      - MYSQL_PASSWORD=${DB_SSPANEL_PWD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./mariadb:/var/run/mysqld   # 提供 sock 到 ./mariadb/mysqld.sock
